### ISSUE TITLE
Fail action when tool download fails

### ISSUE THREAD

**Issue by RichiCoder1** [yokawasa/action-setup-kube-tools#14]
At least right now, when the action fails to download (say due to a bad version), it'll still continue on happily and not fail until something tries to use that tool later. It'd be nice if the action failed immediately.

**Comment by yokawasa** [comment]
@RichiCoder1 thank you so much for your feedback!
I'm thinking to add new `fail-fast` parameter that allow you to choose to fail fast (immediately) or not fail . does it work?

**Comment by RichiCoder1** [comment]
Def! I think most people would expect the defualt to be `fail-fast: true`

**Comment by yokawasa** [comment]
v0.7.0 has been released 🎊
https://github.com/yokawasa/action-setup-kube-tools/releases/tag/v0.7.0
