### ISSUE TITLE
helm v2 is outdated

### ISSUE THREAD

**Issue by MichaelSp** [yokawasa/action-setup-kube-tools#18]
Since `helm V2` is outdated since quite a while, wouldn't it make sense to install `helm` **v3** if people ask for `helm`?

I find it quite confusion to write `helmv3` in my `run: scripts`.

**Comment by yokawasa** [comment]
@MichaelSp Perfectly agree. Thanks!

**Comment by yokawasa** [comment]
@MichaelSp 
v0.8.0 has been released where 
- remove helmv3 parameter and install helm v3 with helm parameter 
- Instead add helmv2 parameter to install helm v2
https://github.com/yokawasa/action-setup-kube-tools/releases/tag/v0.8.0

thank you so much for your suggestion and very sorry for the late action for this
