### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by stephenbawks** [yokawasa/action-setup-kube-tools#3]
Any chance you cannot add the Rancher CLI to your action as well?
https://rancher.com/docs/rancher/v2.x/en/cli/

**Comment by yokawasa** [comment]
@stephenbawks 
thanks for the feature request. I'd love to add the feature. 
I'll work on it

**Comment by yokawasa** [comment]
@stephenbawks 

Rancher CLI is supported @ v0.3.0!!
- https://github.com/yokawasa/action-setup-kube-tools

**Comment by stephenbawks** [comment]
Awesome. Thank you!
