### ISSUE TITLE
Upgrade to using Node16

### ISSUE THREAD

**Issue by omus** [yokawasa/action-setup-kube-tools#30]
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12

**Comment by yokawasa** [comment]
@omus thank you for the issue. 
The issue has been fixed in PR https://github.com/yokawasa/action-setup-kube-tools/pull/31 and the update is available in `0.8.3`. please use `0.8.3`

https://github.com/yokawasa/action-setup-kube-tools/releases/tag/v0.8.3
