### ISSUE TITLE
Add kubeconform

### ISSUE THREAD

**Issue by FalconerTC** [yokawasa/action-setup-kube-tools#32]
Kubeval (https://github.com/instrumenta/kubeval) says it's no longer maintained and recommend using kubeconform (https://github.com/yannh/kubeconform) instead. It would be nice to be able to set this up instead or alongside kubeval

**Comment by yokawasa** [comment]
@FalconerTC thank you for the issue. I'll add `kubeconform` shortly

**Comment by yokawasa** [comment]
@FalconerTC [kubeconform](https://github.com/yannh/kubeconform) was added in v0.9.0

https://github.com/yokawasa/action-setup-kube-tools/releases/tag/v0.9.0

Again thank you so much for the issue!
