### ISSUE TITLE
Using the action produces `set-output` deprecation warnings

### ISSUE THREAD

**Issue by msg-freiheit** [yokawasa/action-setup-kube-tools#36]
Using the action with version `v0.9.0` (and currently pinned to `b7355a1`) produces `set-output` deprecation warnings:

```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-
```

Other deprecation warnings like theses were addressed for this issue https://github.com/yokawasa/action-setup-kube-tools/issues/33, but it seems there are ones remaining.

**Comment by yokawasa** [comment]
@msg-freiheit  Thank you for the inssue!! I'll take a look!

**Comment by msg-freiheit** [comment]
Thank you! I only had a very cursory look, but couldn't see any problems in the code of this action itself right away, so it might even be sufficient to just rebuild the `dist/index.js` file, maybe there were some unintended changes in there from [this PR](https://github.com/yokawasa/action-setup-kube-tools/pull/35). I could create a PR for that if you like?

**Comment by yokawasa** [comment]
@msg-freiheit That would be great if you could try and create PR for the issue - Thank you!

**Comment by yokawasa** [comment]
@msg-freiheit  v0.9.1 has been released! Thanks!
https://github.com/marketplace/actions/setup-kubernetes-tools
