### ISSUE TITLE
Update tooling versions

### ISSUE THREAD

**Issue by FalconerTC** [yokawasa/action-setup-kube-tools#42]
Some of the tools installed in here a few years out of date. `kube-score` for example installs a version from Jan 23, 2021 which only supports Kubernetes <1.21.

**Comment by yokawasa** [comment]
@FalconerTC  thanks for the issue! I've updated default tool vesrions https://github.com/yokawasa/action-setup-kube-tools/pull/44

Please check release versions too https://github.com/yokawasa/action-setup-kube-tools/releases
