### ISSUE TITLE
Not latest version in GitHub Marketplace

### ISSUE THREAD

**Issue by Raboo** [yokawasa/action-setup-kube-tools#7]
Currently v0.2.0 is listed as the latest version in the marketplace.
https://github.com/marketplace/actions/kubernetes-toolset-installer

Is something missing from the release flow?

**Comment by yokawasa** [comment]
@Raboo I forgot to publish the latest version to the market. Now I did publish. Thanks!

<img width="807" alt="Screen Shot 2021-03-11 at 22 28 43" src="https://user-images.githubusercontent.com/82332/110794945-9d076400-82b9-11eb-9e00-16010c652307.png">
